#!/usr/bin/env python3
"""
Convert NAM .nam files to C++ header format for Daisy Seed

This tool extracts the A2-Lite (submodel 0) model JSON from NAM captures
and generates a C++ header file that can be compiled into the firmware.

The generated header stores the JSON as raw C string literals in .rodata
(i.e., in QSPI flash), so no SRAM heap is consumed to hold the model
JSON. Only the NAM DSP tensors themselves are allocated on the heap when
loadModel() is called.

Usage:
    python3 nam_to_header.py Captures/ > src/model_data.h
"""

import json
import os
import sys
from pathlib import Path


def find_nam_files(captures_dir):
    """Find all .nam files in the captures directory."""
    nam_files = []
    captures_path = Path(captures_dir)

    if not captures_path.exists():
        print(f"Error: Captures directory '{captures_dir}' not found", file=sys.stderr)
        sys.exit(1)

    for nam_file in sorted(captures_path.rglob("*.nam")):
        rel_path = nam_file.relative_to(captures_path)
        model_name = rel_path.parent.name if rel_path.parent.name != '.' else 'Default'
        variant_name = nam_file.stem

        nam_files.append({
            'path': nam_file,
            'model_name': model_name,
            'variant_name': variant_name,
        })

    return nam_files


def extract_a2_lite_model(nam_file_path):
    """Extract A2-Lite model JSON from a .nam file."""
    with open(nam_file_path, 'r') as f:
        data = json.load(f)

    if data.get('architecture') == 'SlimmableContainer':
        submodels = data.get('config', {}).get('submodels', [])
        if submodels:
            submodel = submodels[0]
            if 'model' in submodel:
                return submodel['model']
    elif data.get('architecture') == 'WaveNet':
        return data

    print(f"Warning: Could not extract model from {nam_file_path}", file=sys.stderr)
    return None


def to_raw_literal(name, s):
    """
    Emit a C raw string literal.

    Raw strings (R"delim(...)delim") have no escaping requirements at all,
    provided the closing sequence ")delim\"" doesn't appear inside the body.
    The JSON serialized here never contains parentheses, so an empty
    delimiter is safe; use "namjson" to be conservative.
    """
    return f'static const char {name}[] = R"namjson({s})namjson";\n'


def generate_header(nam_files):
    parts = []
    parts.append("// Auto-generated NAM model data\n")
    parts.append("// Generated by tools/nam_to_header.py\n")
    parts.append("// DO NOT EDIT - regenerate with:\n")
    parts.append("//   python3 tools/nam_to_header.py Captures/ > src/model_data.h\n\n")
    parts.append("#pragma once\n\n")
    parts.append("#include <cstddef>\n\n")
    parts.append("struct NAMModel {\n")
    parts.append("    const char* model_name;\n")
    parts.append("    const char* variant_name;\n")
    parts.append("    const char* model_json;    // Null-terminated JSON in .rodata.\n")
    parts.append("    size_t      model_json_len;\n")
    parts.append("};\n\n")

    entries = []
    for idx, nam_file in enumerate(nam_files):
        print(f"Processing: {nam_file['path']}", file=sys.stderr)

        model_json = extract_a2_lite_model(nam_file['path'])
        if not model_json:
            print(f"  Warning: No model found, skipping", file=sys.stderr)
            continue

        if model_json.get('architecture') != 'WaveNet':
            print(f"  Warning: Not a WaveNet architecture, skipping", file=sys.stderr)
            continue

        config = model_json.get('config', {})
        if 'layers' in config and config['layers']:
            layer = config['layers'][0]
            channels = layer.get('channels', 0)
            if channels != 3:
                print(f"  Warning: Not A2-Lite (channels={channels}), skipping", file=sys.stderr)
                continue

        model_json_str = json.dumps(model_json, separators=(',', ':'))
        if ')namjson"' in model_json_str:
            print(f"  Error: JSON contains raw-string delimiter sentinel", file=sys.stderr)
            sys.exit(1)

        var = f"kNamModelJson_{idx}"
        parts.append(to_raw_literal(var, model_json_str))
        parts.append("\n")

        entries.append({
            'name': nam_file['model_name'],
            'variant': nam_file['variant_name'],
            'json_var': var,
            'json_len': len(model_json_str),
        })

        print(f"  A2-Lite model, {len(model_json.get('weights', []))} weights, "
              f"{len(model_json_str)} JSON bytes",
              file=sys.stderr)

    if not entries:
        print("Error: No valid NAM A2-Lite models found", file=sys.stderr)
        sys.exit(1)

    parts.append(f"static constexpr int NAM_MODEL_COUNT = {len(entries)};\n")
    parts.append("static const NAMModel nam_models[NAM_MODEL_COUNT] = {\n")
    for e in entries:
        parts.append(
            f'    {{ "{e["name"]}", "{e["variant"]}", '
            f'{e["json_var"]}, sizeof({e["json_var"]}) - 1 }},\n'
        )
    parts.append("};\n")

    return ''.join(parts)


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 nam_to_header.py <captures_directory>", file=sys.stderr)
        sys.exit(1)

    captures_dir = sys.argv[1]
    nam_files = find_nam_files(captures_dir)

    if not nam_files:
        print(f"Error: No .nam files found in {captures_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(nam_files)} NAM files", file=sys.stderr)

    header = generate_header(nam_files)
    sys.stdout.write(header)


if __name__ == "__main__":
    main()
