#!/usr/bin/env python3
"""
Convert NAM .nam files to C++ header format for Daisy Seed

This tool extracts the A2-Lite (submodel 0) model JSON from NAM captures
and generates a C++ header file that can be compiled into the firmware.

Usage:
    python3 nam_to_header.py Captures/ > src/model_data.h
"""

import json
import os
import sys
from pathlib import Path


def find_nam_files(captures_dir):
    """Find all .nam files in the captures directory"""
    nam_files = []
    captures_path = Path(captures_dir)
    
    if not captures_path.exists():
        print(f"Error: Captures directory '{captures_dir}' not found", file=sys.stderr)
        sys.exit(1)
    
    # Find all .nam files recursively
    for nam_file in sorted(captures_path.rglob("*.nam")):
        # Get relative path for model name
        rel_path = nam_file.relative_to(captures_path)
        # Parent folder name is the model name
        model_name = rel_path.parent.name if rel_path.parent.name != '.' else 'Default'
        # File name (without .nam) is the variant
        variant_name = nam_file.stem
        
        nam_files.append({
            'path': nam_file,
            'model_name': model_name,
            'variant_name': variant_name
        })
    
    return nam_files


def extract_a2_lite_model(nam_file_path):
    """Extract A2-Lite model JSON from a .nam file"""
    with open(nam_file_path, 'r') as f:
        data = json.load(f)
    
    # Check if it's a SlimmableContainer (has submodels)
    if data.get('architecture') == 'SlimmableContainer':
        # Use submodel 0 (A2-Lite, smaller model for lower input levels)
        if 'config' in data and 'submodels' in data['config']:
            if len(data['config']['submodels']) > 0:
                submodel = data['config']['submodels'][0]
                if 'model' in submodel:
                    return submodel['model']
    # Check if it's a standard WaveNet (A1)
    elif data.get('architecture') == 'WaveNet':
        return data
    
    print(f"Warning: Could not extract model from {nam_file_path}", file=sys.stderr)
    return None


def escape_json_string(s):
    """Escape a string for use in C++ source code"""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')


def generate_header(nam_files):
    """Generate C++ header file with model JSON"""
    
    header = """// Auto-generated NAM model data
// Generated by nam_to_header.py
// DO NOT EDIT - regenerate with: python3 tools/nam_to_header.py Captures/ > src/model_data.h

#pragma once

#include <vector>
#include <string>

struct NAMModel {{
    const char* model_name;
    const char* variant_name;
    std::string model_json;
}};

// Model collection
static const int NAM_MODEL_COUNT = {model_count};
static NAMModel nam_models[NAM_MODEL_COUNT] = {{
{models_data}
}};

"""

    models_data = []
    
    for idx, nam_file in enumerate(nam_files):
        print(f"Processing: {nam_file['path']}", file=sys.stderr)
        
        model_json = extract_a2_lite_model(nam_file['path'])
        
        if not model_json:
            print(f"  Warning: No model found, skipping", file=sys.stderr)
            continue
        
        # Verify it's A2-Lite
        if model_json.get('architecture') != 'WaveNet':
            print(f"  Warning: Not a WaveNet architecture, skipping", file=sys.stderr)
            continue
        
        config = model_json.get('config', {})
        if 'layers' in config and len(config['layers']) > 0:
            layer = config['layers'][0]
            channels = layer.get('channels', 0)
            if channels != 3:
                print(f"  Warning: Not A2-Lite (channels={channels}), skipping", file=sys.stderr)
                continue
        
        # Convert to JSON string
        model_json_str = json.dumps(model_json, separators=(',', ':'))
        escaped_json = escape_json_string(model_json_str)
        
        print(f"  Found A2-Lite model with {len(model_json.get('weights', []))} weights", file=sys.stderr)
        
        model_entry = f"""    {{
        "{nam_file['model_name']}",
        "{nam_file['variant_name']}",
        "{escaped_json}"
    }}"""
        
        models_data.append(model_entry)
    
    if not models_data:
        print("Error: No valid NAM A2-Lite models found", file=sys.stderr)
        sys.exit(1)
    
    # Join all models
    models_str = ",\n".join(models_data)
    
    # Generate final header
    final_header = header.format(
        model_count=len(models_data),
        models_data=models_str
    )
    
    return final_header


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 nam_to_header.py <captures_directory>", file=sys.stderr)
        print("Example: python3 nam_to_header.py Captures/ > src/model_data.h", file=sys.stderr)
        sys.exit(1)
    
    captures_dir = sys.argv[1]
    
    # Find all .nam files
    nam_files = find_nam_files(captures_dir)
    
    if not nam_files:
        print(f"Error: No .nam files found in {captures_dir}", file=sys.stderr)
        sys.exit(1)
    
    print(f"Found {len(nam_files)} NAM files", file=sys.stderr)
    
    # Generate header
    header = generate_header(nam_files)
    
    # Output to stdout
    print(header)


if __name__ == "__main__":
    main()
